name: CodeGuard Scan
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  codeguard-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run CodeGuard Scanner
        run: |
          npx @codeguard/scanner scan \
            --project="My angular map project" \
            --framework="angular" \
            --token=${{ cg_1234567890abcdef }}

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: codeguard-results
          path: codeguard-results.json
